import pandas as pd
import numpy as np

print("--- Lab V5: Injecting Quantitative Indicators (RSI & Macro) ---")

# 1. Load Datasets
print("Loading datasets...")
btc = pd.read_csv("dados_preparados_btc.csv")
sp500 = pd.read_csv("historico_sp500.csv")

# 2. The Merge (Intersection of Crypto and Global Markets)
master_df = pd.merge(btc, sp500, on='Date', how='left')

# 3. Handling Missing Values (Stock market is closed on weekends)
master_df['Close_SP500'] = master_df['Close_SP500'].ffill().bfill()

# 4. Classic Macroeconomic Features
master_df['Return_SP500'] = master_df['Close_SP500'].pct_change()
master_df['Return_SP500_Yesterday'] = master_df['Return_SP500'].shift(1)
master_df['Correlation_BTC_SP500'] = master_df['Daily_Return'].rolling(window=30).corr(master_df['Return_SP500'])

# =====================================================================
# 5. THE NEW WEAPON: RSI (Relative Strength Index - 14 Days)
# =====================================================================
print("Calculating market exhaustion (14-Day RSI)...")

# Step A: Separate gaining days from losing days
delta = master_df['Close'].diff()
gains = delta.clip(lower=0)
losses = -1 * delta.clip(upper=0)

# Step B: Calculate the 14-day exponential moving average of gains and losses
avg_gains = gains.ewm(com=13, adjust=False).mean()
avg_losses = losses.ewm(com=13, adjust=False).mean()

# Step C: The final RSI mathematical formula
rs = avg_gains / avg_losses
master_df['RSI_14'] = 100 - (100 / (1 + rs))

# =====================================================================

# Drop missing values generated by the new rolling calculations
master_df = master_df.dropna()

# 6. Save the Final Matrix for the AI Model
filename = "dados_finais_ml.csv"
master_df.to_csv(filename, index=False)

print("\n--- RSI Output Sample ---")
print(master_df[['Date', 'Close', 'RSI_14', 'Target']].tail())
print(f"\nSupreme Matrix Updated! File '{filename}' is ready for Machine Learning.")